#!/bin/bash

# List files in the current directory in long format
echo "Current Directory:"
ls -la

# List files in the parent directory in long format
echo "Parent Directory:"
ls -la ..

# List files in the /boot directory in long format
echo "/boot Directory:"
ls -la /boot
